# version: "3"
# services:
#     web:
#         env_file: .env
#         build:
#             context: .
#             dockerfile: Dockerfile
#         # command: set -a; source time_control/.env; set +a
#         # command: python manage.py runserver 0.0.0.0:5151
#         # command: task build
#         command: uvicorn main:app --host 0.0.0.0 --port 5151
#         volumes:
#             - .:/code
#         ports:
#             - "5151:5151"

services:
    web:
        build: .
        ports:
            - "5151:5151"
