"""empty message

Revision ID: 419394ef4ab5
Revises: 
Create Date: 2023-06-21 18:23:36.979594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419394ef4ab5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculo',
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('site', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'vendido', 'indisponivel', 'duplicado', name='veiculostatus'), nullable=True),
    sa.Column('favorito', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('veiculohistorico',
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('quilometragem', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('datahora', sa.DateTime(), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculoimagem',
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'token_invalido', name='veiculoimagemstatus'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'veiculo_id')
    )
    op.create_table('usuario',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('is_offer', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('veiculoimagem')
    op.drop_table('veiculohistorico')
    op.drop_table('veiculo')
    # ### end Alembic commands ###
